spring.application.name=opscore-backend
server.port=8080

spring.datasource.url=${OPSCORE_DB_URL:jdbc:postgresql://localhost:5432/opscore_dev}
spring.datasource.username=${OPSCORE_DB_USERNAME:opscore_user}
spring.datasource.password=${OPSCORE_DB_PASSWORD:opscore_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

server.error.include-stacktrace=never
server.error.include-message=never
